### ISSUE TITLE
trigger sharing when file is uploaded

### ISSUE THREAD

**Issue by luggie** [owncloud/pyocclient#238]
Hi there, 
I'm completely new to this topic so excuse me if the the following question should be very basic.
What I need to do is, to automatically share everything a user is uploading the every group he's in.
So the my main question would be how to trigger events from owncloud like an uploading event.
thanks, luggie

**Comment by PVince81** [comment]
This is not technically possible with ownCloud's APIs currently.

Another way to achieve this:
- create a service user "service"
- service user creates a folder "all-uploads"
- service user shares folder "all-uploads" with all groups of "uploader-user", including "uploader-user"
- admin sets quota of "uploader-user" to 0, so that they can only ever upload into the "all-uploads" folder and not outside

This would achieve a similar result where all files/folders uploaded by "uploader-user" into "all-uploads" folder will be automatically accessible to everyone.

In general I'd recommend against the strategy you proposed because it could result in a very high number of shares which could slow down file browsing and syncing as there would be too many shares to resolve for the recipients. In my proposed solution, there is only ever a single share involved.

I'll close this ticket as it's too far away from what pyocclient can do.
For further discussions, please ask in https://central.owncloud.org/.
Thanks!
