### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by PVince81** [owncloud/pyocclient#54]
@blizzz

**Comment by PVince81** [comment]
Moving this to 0.3

**Comment by cosenal** [comment]
@blizzz What's the status of this? I can reproduce the errors you mentioned in your PR, but I also see @paparazzo's commits to your repos. Do they fix some of those errors?

According to @PVince81, the codebase has changed since then, maybe it's worth starting from scratch again?
I am willing to take over (I'm trying to increase my python expertise these days..) , just don't know what's the best way to start.

**Comment by dtext** [comment]
Any updates on this? Would love to use pyocclient for a python 3 app!

**Comment by PVince81** [comment]
@cosenal I asked @blizzz and you can take over this or start over, as you like.

**Comment by cosenal** [comment]
ok, as soon as I have something, I will open a new PR

**Comment by ethifus** [comment]
Hi. I needed recent pocclient to work with python 3. Perhaps you will be interested in reviewing my changes that introduces python 3.4 compatibility (PR: #146).

**Comment by PVince81** [comment]
@ethifus thanks a lot :smile:

**Comment by Reylak** [comment]
Hey, is this planned for actual merging soon? I'd love to have pyocclient run on Python 3 :D

**Comment by PVince81** [comment]
Can someone take over https://github.com/owncloud/pyocclient/pull/146, unless @ethifus has time ?
Need to solve the conflicts and hope the unit tests still pass :smile: 

Would also be good to have Python3 testing on Travis, might be tricky: https://github.com/owncloud/pyocclient/pull/60

I currently don't have time to make it work but if a working PR is provided (that doesn't break when using Python 2) then I'd be happy to merge it.

**Comment by blizzz** [comment]
Did a rebase of #146 in https://github.com/owncloud/pyocclient/pull/173, pls have a look

**Comment by PVince81** [comment]
Python 3 support was merged, closing.
